apiVersion: v1
kind: Service
metadata:
  name: {{ include "ip-api-proxy.fullname" . }}
  labels: {{ include "ip-api-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{ include "ip-api-proxy.selectorLabels" . | nindent 4 }}
